# LEAGUE MECHANICS CONFIGURATION
# https://github.com/expo-sitory

general-settings:
  debug: true
  damage-divisor-balancer: 2.1 # A value to divide players total damage output
  resistance-multiplier-balancer: 1.8 # A value to multiply players total damage resistance

  mysql: # MySQL Configuration - Runes & KDA Multi Server Synchronization
    host: kupalhost
    port: 3306
    database: leaguemechanics
    username: root
    password: ""
    pool-size: 10
    idle-timeout: 300000
    max-lifetime: 1800000
    connection-timeout: 30000

runes:

  keystones:

    # ============================= #
    #        DOMINATION PATH        #
    # ============================= #

    domination:

      dark-harvest:
        base-adaptive-damage-per-stack: 2.5 # hardcoded max stack: 20
        cooldown: 60 # seconds - Cooldown before next soul reap

      electrocute:
        base-adaptive-damage: 24.5
        cooldown: 25 # seconds

      hail-of-blades:
        base-attack-speed: 10.0 # default: 10%
        base-true-damage: 7.0 #  default: 7%
        ad-percentage-multiplier: 8.0 # bonus true damage percentage from total AP percent - default: 8%
        ap-percentage-multiplier: 6.0 # bonus true damage percentage from total AP percent - default: 6%
        cooldown: 60 # seconds


    # ============================= #
    #       PRECISION PATH          #
    # ============================= #

    precision:
      conqueror:
        base-adaptive-damage-per-stack: 1.8 # hard coded max stack: 12

      fleet-footwork:
        blocks-per-stack: 10.0 # blocks to pass to gain 1 stack
        projectile-stack-gain: 5 # stack to gain when hitting projectiles
        heal-percent: 25.0 # missing health percentage - default: 25%
        ad-percentage-multiplier: 10.0 # bonus healing percentage from total AD percent - default: this is 10%
        ap-percentage-multiplier: 5.0 # bonus healing percentage from total AP percent - default: this is 5%

      lethal-tempo:
        base-adaptive-damage: 2.7 # adaptive damage when on max/active state
        attack-speed: 60.0 # when on max stacks/active state - # percentage - default: 60%
        cooldown: 30 # seconds

      press-the-attack:
        base-adaptive-damage: 9.5
        cooldown: 6 # seconds

    # ============================= #
    #       INSPIRATION PATH        #
    # ============================= #

    inspiration:

      glacial-augment:
        base-freeze-duration: 120 # in ticks
        ad-percentage-multiplier: 7.0 # bonus freeze duration from total AD percent - default 7%
        ap-percentage-multiplier: 6.0 # bonus freeze duration from total AP percent - default 6%
        cooldown: 45 # seconds

      first-strike:
        initial-xp: 24.0 # starting xp
        buff-duration: 3 #seconds
        true-damage-percent: 7.0 # while on active state
        ad-percentage: 20.0 # bonus true damage from total AD percent - default: 20%
        ap-percentage: 15.0 # bonus true damage from total AP percent - default: 15%
        cooldown: 25 # seconds

    # ============================= #
    #       RESOLVE PATH            #
    # ============================= #

    resolve:

      aftershock:
        bonus-armor-percent: 75.0 # bonus armor percentage
        bonus-magic-resist-percent: 75.0 # bonus magic-resist percentage
        base-shockwave-damage: 12.5 # base shockwave magic damage
        shockwave-bonus-hp-percent: 25.0 # bonus magic damage from total hp percentage
        cooldown: 20 # seconds

      grasp-of-the-undying:
        heal-percent: 60.0 # missing health percent - default: 60%
        cooldown: 45 # seconds

      guardian:
        max-players: 5 # max number of players that will get the effect
        absorption-percentage: 300.0 # 100 = One full line (20)
        cooldown: 60 # seconds


    # ============================= #
    #       SORCERY PATH            #
    # ============================= #

    sorcery:

      arcane-comet:
        base-adaptive-damage: 17.5
        ad-percentage-multiplier: 5.0 # bonus adaptive damage from total AD percent - default: 5%
        ap-percentage-multiplier: 15.0 # bonus adaptive damage from total AP percent - default: 15%
        cooldown: 20 # seconds

      deathfire-torch:
        base-magic-damage: 2.5 # base magic damage per tick
        ad-percentage-multiplier: 3.0 # bonus magic damage from total AD percent - default: 3%
        ap-percentage-multiplier: 6.0 # bonus magic damage from total AP percent - default: 6%

      storm-raider-surge:
        damage-percent-threshold: 30.0 # damage threshold to activate - default: 30%
        cooldown: 25 # seconds

# Mob Statistics Configuration
mob-stats:
  zombie:
    ad: 37.0
    ap: 12.0
    ar: 150.0
    mr: 70.0
    type: UNDEAD
  skeleton:
    ad: 15.0
    ap: 35.0
    ar: 40.0
    mr: 175.0
    type: UNDEAD
  spider:
    ad: 38.0
    ap: 22.0
    ar: 30.0
    mr: 100.0
    type: ARTHROPOD
  cave_spider:
    ad: 34.0
    ap: 46.0
    ar: 400.0
    mr: 60.0
    type: ARTHROPOD
  creeper:
    ad: 0.0
    ap: 0.0
    ar: 399.0
    mr: 399.0
    type: CRITTER
  enderman:
    ad: 70.0
    ap: 70.0
    ar: 120.0
    mr: 820.0
    type: ENDERMAN
  witch:
    ad: 0.0
    ap: 485.0
    ar: 55.0
    mr: 530.0
    type: WITCH
  slime:
    ad: 70.0
    ap: 70.0
    ar: 999.0
    mr: 10.0
    type: SLIME
  magma_cube:
    ad: 85.0
    ap: 65.0
    ar: 600.0
    mr: 600.0
    type: SLIME
  blaze:
    ad: 70.0
    ap: 120.0
    ar: 999.0
    mr: 500.0
    type: BLAZE
  ghast:
    ad: 0.0
    ap: 190.0
    ar: 200.0
    mr: 800.0
    type: GHAST
  stray:
    ad: 25.0
    ap: 0.0
    ar: 150.0
    mr: 25.0
    type: UNDEAD
  husk:
    ad: 52.0
    ap: 30.0
    ar: 87.0
    mr: 57.0
    type: UNDEAD
  zombie_villager:
    ad: 42.0
    ap: 60.0
    ar: 120.0
    mr: 57.0
    type: UNDEAD
  wither_skeleton:
    ad: 197.0
    ap: 20.0
    ar: 487.0
    mr: 120.0
    type: UNDEAD